name:                haste
version:             0.1.0.0
github:              "raduom/haste"
license:             OtherLicense

extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall

# Metadata used when publishing your package
synopsis:            K Framework backend used for execution that compiles to LLVM IR.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haste#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  haste-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haste
